export const ALL_PRODUCTS: IProduct[] = [
  {
    id: 1,
    slug: "tedee-pro-smart-lock-set-with-pin-keypad-wi-fi-with-remote-control-and-bluetooth",
    imageUrl: "/static/images/products/TEDEE_PRO_silver.jpg",
    title: "TEDEE PRO viedās slēdzenes komplekts ar PIN koda tastatūru, Wi-Fi ar tālvadības pulti un Bluetooth",
    price: 580,
    description: "Standarta uzticama slēdzene ar uzlabotu furnitūru, kas nodrošina papildu aizsardzību pret uzlaušanu un neatļautu slēdzenes atvēršanu. Ideāli piemērota tiem, kas vēlas paaugstināt drošības līmeni savās mājās vai pēc pieprasījuma. Aprīkota ar Wi-Fi un Bluetooth savienojamību, PIN koda tastatūru, EURO tipa universālo cilindru un ir piemērota dažādu veidu durvīm.",
    category: "Slēdzenes",
    subcategory: "TEDEE",
  },
  {
    id: 2,
    imageUrl: "/static/images/products/TEDEE_PRO_ar_Bluetooth_black.jpg",
    slug: "smart-tedee-pro-lock-with-bluetooth-black",
    title: "Viedā slēdzene TEDEE PRO ar Bluetooth melnā krāsā",
    price: 300,
    description: "Standarta uzticama slēdzene ar uzlabotu furnitūru, kas nodrošina papildu aizsardzību pret uzlaušanu un neatļautu slēdzenes atvēršanu. Ideāli piemērota tiem, kas vēlas paaugstināt drošības līmeni savās mājās vai pēc pieprasījuma.",
    category: "Slēdzenes",
    subcategory: "TEDEE",
  },
  {
    id: 3,
    imageUrl: "/static/images/products/TEDEE_PRO_ar_Bluetooth_silver.png",
    slug: "smart-tedee-pro-lock-with-silver-bluetooth",
    title: "Viedā slēdzene TEDEE PRO ar Bluetooth sudraba krāsā",
    price: 300,
    description: "Standarta uzticama slēdzene ar uzlabotu furnitūru, kas nodrošina papildu aizsardzību pret uzlaušanu un neatļautu slēdzenes atvēršanu. Ideāli piemērota tiem, kas vēlas paaugstināt drošības līmeni savās mājās vai pēc pieprasījuma.",
    category: "Slēdzenes",
    subcategory: "TEDEE",
  },
  {
    id: 4,
    imageUrl: "/static/images/products/Droša slēdzene ar pastiprinātu furnitūru un aizsardzību pret uzlaušanu.jpg",
    slug: "reliable-lock-with-reinforced-fittings-and-burglary-protection",
    title: "Droša slēdzene ar pastiprinātu furnitūru un aizsardzību pret uzlaušanu",
    price: 150,
    description: "Standarta uzticama slēdzene ar uzlabotu furnitūru, kas nodrošina papildu aizsardzību pret uzlaušanu un neatļautu slēdzenes atvēršanu. Ideāli piemērota tiem, kas vēlas paaugstināt drošības līmeni savās mājās vai pēc pieprasījuma. Aprīkota ar KFV 115/72 slēdzeni, FAB ASSAABLOY cilindru (35 x 30 mm) un pastiprinātu FAB ASSAABLOY furnitūru.",
    category: "Slēdzenes",
    subcategory: "Slēdzenes nomaiņa",
  },
  {
    id: 5,
    imageUrl: "/static/images/products/sensor.png",
    slug: "ajax-motionprotect-balts",
    title: "AJAX MotionProtect Balts",
    price: 60,
    description: "Darbības ilgums ar vienu akumulatoru - līdz 5 gadiem 3 jutības līmeņi Darbojas līdz 2000 metru attālumā no Ajax Hub.",
    category: "Signalizācija",
    subcategory: "AJAX",
  },
  {
    id: 6,
    imageUrl: "/static/images/products/EZSVIZ camera.jpg",
    slug: "ezviz-wi-fi-cs-hp7-domofona-komplekts",
    title: "EZVIZ Wi-Fi CS-HP7 domofona komplekts",
    price: 340,
    description: "Palieliniet savas mājas drošību, izmantojot viedāku drošas piekļuves risinājumu. Nomainiet savu veco domofonu sistēmu ar internetam pieslēgtu, ar tālvadību vadāmu, ar lietotni vadāmu risinājumu. EZVIZ pirmais video durvju zvans HP7 nodrošina māju īpašniekiem lielākas ērtības, ļaujot tiem skatīt, sazināties un koplietot piekļuvi ar apmeklētājiem no jebkuras vietas, pat atrodoties prom no mājām. Šī āra kamera un tālruņu sistēma \"divi vienā\" ne tikai ieraksta 2K video, bet arī nosaka cilvēkus un nosūta tūlītējus mobilos paziņojumus, lai palīdzētu uzlabot mājas drošību",
    category: "Piekļuves tiesības",
    subcategory: "EZVIZ",
  },
  {
    id: 7,
    imageUrl: "/static/images/products/bezvadu_tastatura.png",
    slug: "ajax-keypad-touchscreen-w-bezvadu-tastatura-balta",
    title: "AJAX Keypad TouchScreen W (8EU) - Bezvadu tastatūra",
    price: 315,
    description: "Bezvadu tastatūra ar skārienekrānu Ajax sistēmas vadīšanai. KeyPad TouchScreen – apvieno drošību un iespēju vadīt viedās mājas ierīces. Intuitīvais interfeiss atbalsta vairākas valodas, dublē Ajax lietojumprogrammu un atvieglo tastatūras lietošanu.",
    category: "Signalizācija",
    subcategory: "AJAX",
  },
  {
    id: 8,
    imageUrl: "/static/images/products/gaisakvalitate.jpg",
    slug: "gaisa-kvalitates-monitors-ajax-lifequality-w",
    title: "Gaisa kvalitātes monitors Ajax LifeQuality (BEU) W",
    price: 380,
    description: "LifeQuality (8EU) W ir uzlabots gaisa kvalitātes monitors, kas nodrošina precīzu un uzreiz saprotamu informāciju par apkārtējā gaisa stāvokli. Ar šo monitoru varat uzraudzīt un uzlabot gaisa kvalitāti mājās vai darbavietā. Ar vienkāršu dizainu un ērtu izmantošanu LifeQuality (8EU) W nodrošina ērtības un drošību ikvienam, kurš vēlas uzturēt labu gaisa kvalitāti savā apkārtnē. Specifikācija: Modelis: 8EU, Krāsa: balta, Izmantošana: gaisa kvalitātes monitors",
    category: "Signalizācija",
    subcategory: "AJAX",
  },
  {
    id: 9,
    imageUrl: "/static/images/products/siltumadetektors.png",
    slug: "bezvadu-dumu-un-siltuma-detektors-ajax-fireprotect-w",
    title: "Bezvadu dūmu un siltuma detektors ar sirēnu Ajax FireProtect W",
    price: 102,
    description: "FireProtect W ir uzticams un mūsdienīgs bezvadu dūmu un siltuma detektors, aprīkots ar fotoelektriskajiem un temperatūras sensoriem, nodrošinot augstu drošības līmeni pret ugunsgrēku. Iebūvētā sirēna ar 85 dB skaļumu sniedz skaidru brīdinājumu. Tas darbojas ar divām CR2 3 V baterijām, kas nodrošina līdz četru gadu ilgu kalpošanas laiku. Arī montāžas kronšteins ir iekļauts komplektā, padarot uzstādīšanu vienkāršu un ērtu. FireProtect W ir gan efektīvs, gan viegli lietojams dūmu un siltuma detektors mājas vai biroja drošības nodrošināšanai. Specifikācija: Detektoru veids: bezvadu dūmu un siltuma detektors (fotoelektriskie un temperatūras sensori), Aktivizēšanas slieksnis: +54–65 °C, Sirēna: iebūvēta, 85 dB, ar indikāciju, Barošana: 2 x CR2 3 V baterijas (bateriju kalpošanas laiks – četri gadi) – iekļautas komplektā, Darbības frekvence: 868 MHz, Kronšteins: iekļauts komplektā, Krāsa: balta",
    category: "Signalizācija",
    subcategory: "AJAX",
  },
  {
    id: 10,
    imageUrl: "/static/images/products/udensDetektors.png",
    slug: "uzticams-bezvadu-udens-nopludes-detektors-ajax-leaksprotect-w",
    title: "Uzticams bezvadu ūdens noplūdes detektors Ajax LeaksProtect W",
    price: 70,
    description: "LeaksProtect W ir uzlabots bezvadu ūdens noplūdes detektors, kas nodrošina ātru un efektīvu aizsardzību pret potenciālajiem ūdens bojājumiem mājās vai birojā. Šis detektors ir vienkārši uzstādāms un darbojas autonomi, neprasa sarežģītas vadu instalācijas vai pieslēgšanu pie elektrības tīkla. Tā bezvadu darbība un ilgstošais bateriju kalpošanas laiks padara to par praktisku un uzticamu risinājumu, nodrošinot jūsu mieru. Specifikācija: Detektoru veids: bezvadu ūdens noplūdes detektors, Barošanas avots: 2 x AAA 3 V baterijas (bateriju kalpošanas laiks – pieci gadi) – iekļautas komplektā, Darbības frekvence: 868 MHz, Krāsa: balta",
    category: "Signalizācija",
    subcategory: "AJAX",
  },
  {
    id: 11,
    imageUrl: "/static/images/products/camera.png",
    slug: "ezviz-wi-fi-videokameras",
    title: "EZVIZ Wi-Fi videokameras",
    price: 150,
    description: "EZVIZ eLife 4MP ir viegli lietojama bezvadu kamera, kas nodrošina ilgu darbības laiku un kristālskaidru 2K+ video kvalitāti. BC1C ir aprīkots ar galvenajām uzlabotajām EZVIZ drošības tehnoloģijām: krāsains nakts režīms, divvirzienu audio sakaru iespējas, aktīvā aizsardzība un daudz kas cits. Kamera ir viegli uzstādāma un lietojama. Ir nepieciešams tikai Wi-Fi savienojums un EZVIZ lietotne. Lejupielādējiet bezmaksas EZVIZ lietotni, lai iestatītu kameru, skatītos tiešraides vai saņemtu paziņojumus par kustībām. Bezvadu kamera BC1C darbojas ar uzlādējamu akumulatoru un nodrošina visaptverošu mājas aizsardzību līdz pat 210 dienām bez uzlādes. Specifikācija: Viegla konfigurācija, Skata leņķis: 100° horizontāli, 116° diagonāli, Paziņojumi uz viedtālruni, ja ir ieslēgts signāla režīms, Cilvēku identifikācijas tehnoloģija, Nakts redzamība līdz 10 m, Skaņas ieraksts un atskaņošana, Iebūvēta 32 GB eMMC krātuve, IP66 aizsardzības pakāpe, Divvirzienu audio sakari, 2,4 GHz Wi-Fi savienojums",
    category: "Videonovērošana",
    subcategory: "EZVIZ",
  },
  {
    id: 12,
    imageUrl: "/static/images/products/vaduKomplekts.jpg",
    slug: "vadu-apsardzes-sistemas-dsc-paradox",
    title: "Vadu apsardzes sistēmas (DSC, PARADOX)",
    price: 250,
    description: "Pēc klienta pasūtījuma izstrādāta vadu apsardzes sistēma, balstīta uz uzticamiem zīmoliem DSC un PARADOX. Šī pielāgotā sistēma nodrošina augstu drošības līmeni, ātru reaģēšanu uz apdraudējumu un vieglu lietojamību. Ar dažādiem sensoriem un kustības detektoriem tā garantē pilnīgu īpašuma aizsardzību. Šī modernā sistēma nodrošina klientam mieru, jo viņš zina, ka viņa īpašums ir drošs un aizsargāts.",
    category: "Signalizācija",
    subcategory: "PARADOX",
  },
  {
    id: 13,
    imageUrl: "/static/images/products/Ajax bezvadu apsardzes sistēmas komplekts.jpg",
    slug: "ajax-bezvadu-apsardzes-sistemas-komplekts",
    title: "Ajax bezvadu apsardzes sistēmas komplekts",
    price: 415,
    description: "Šis Ajax bezvadu apsardzes sistēmas komplekts ir visaptverošs risinājums drošībai mājās vai uzņēmumā. Tas iekļauj vairākus svarīgus komponentus, kas kopā nodrošina efektīvu un uzticamu apsardzi. Ajax komplekts ir izstrādāts, lai nodrošinātu pilnīgu un uzticamu drošību mājās vai uzņēmumā, piedāvājot vairākas funkcijas un uzraudzību, lai jūs varētu justies mierīgi visos apstākļos. Komplekta sastāvs: HUB B – bezvadu GSM/Ethernet uztvērējs, DoorProtect B – bezvadu magnētiskais kontakts, MotionProtect B – bezvadu PIR detektors, HomeSiren B – bezvadu iekšējā sirēna, FireProtect B – bezvadu dūmu un siltuma detektors ar sirēnu, SpaceControl B – bezvadu breloks ar četrām pogām. Specifikācija: Sistēmas veids: bezvadu apsardzes sistēmas komplekts, Saziņas protokols: GSM/Ethernet, Autentifikācija: jā, Jamming detektēšana: jā, Tampering Alarma: jā, Darbības temperatūra: -10 līdz +40 °C",
    category: "Signalizācija",
    subcategory: "AJAX",
  },
  {
    id: 14,
    imageUrl: "/static/images/products/UNV_Starlight.jpg",
    slug: "unv-starlight-ip-4mp-un-28-mm-kamera",
    title: "UNV Starlight IP 4MP un 2,8 mm kamera",
    price: 100,
    description: "Šī IP kamera nodrošina augstas izšķirtspējas video un augstu jutību pat naktī. Ar Starlight video sensora standartu un minimālo gaismas jutību 0,003 lx tā spēj sniegt skaidrus attēlus arī zemā. Turklāt tā ir izturīga pret laikapstākļiem un vandālisma nodarījumiem, nodrošinot IP67 aizsardzību, un ir izgatavota no metāla. Ar plašu darbības temperatūras diapazonu un iebūvētu mikrofonu šī kamera ir lielisks risinājums videonovērošanai dažādos apstākļos. Specifikācija: Video sensora standarts: Starlight, Izšķirtspēja: 4 MP, Kadru ātrums: 30 kadri/sekundē, Iebūvēts mikrofons, IP aizsardzības klase: IP67, Darbības temperatūra: -30 – +60 °C (-22 – +140 °F), Svars (g): 450, Materiāls: metāls",
    category: "Videonovērošana",
    subcategory: "UNV Starlight",
  },
  {
    id: 15,
    imageUrl: "/static/images/products/Hikvision_AcuSense.jpg",
    slug: "hikvision-acusense-ip-4mp-un-28-mm-kamera",
    title: "Hikvision AcuSense IP 4MP un 2,8 mm kamera",
    price: 150,
    description: "Hikvision AcuSense IP 4MP kamera piedāvā augstas izšķirtspējas video uzņemšanu ar AcuSense tehnoloģiju, kas precīzi atpazīst kustības un svarīgus objektus. Ar 40 metru infrasarkano LED apgaismojumu tā nodrošina skaidru redzamību pat naktī. Kamera ir IP67 aizsargāta un spēj darboties ekstrēmos laikapstākļos. Ar iebūvētu mikrofonu un atbalstu SD kartēm līdz 256 GB, tā ir lielisks risinājums drošības vajadzībām. Specifikācija: Video sensora standarts: AcuSense, Izšķirtspēja: 4 MP, Kadru ātrums: 30 kadri/sekundē, Iebūvēts mikrofons, IP aizsardzības klase: IP67, Darbības temperatūra:-30 – +60 °C (-22 – +140 °F), Svars (g): 485, Materiāls: metāls",
    category: "Videonovērošana",
    subcategory: "Hikvision",
  },
  {
    id: 16,
    imageUrl: "/static/images/products/YSV.170.DB2.jpg",
    slug: "seifs-nelielu-vertibu-glabasanai-ysv170db2",
    title: "Seifs nelielu vērtību glabāšanai YSV/170/DB2",
    price: 85,
    description: "Izcils risinājums vērtīgo mantu glabāšanai – nelielu vērtību glabāšanas seifs. Seifs ir aprīkots ar iebūvētu 130 dB trauksmes signālu. Ielaušanās gadījumā vai pēc trim neveiksmīgiem PIN ievades mēģinājumiem skanēs trauksmes signāls, kuru var apstādināt, tikai ievadot pareizo kodu vai atverot seifu ar atslēgu. Esiet pārliecināti, ka jūsu dokumenti, pase vai nauda atrodas drošā vietā, – izmantojiet seifu nelielu vērtību glabāšanai! Specifikācija: Ārējās dimensijas: A 170 x P 230 x Dz 170 mm, Iekšējās dimensijas: A 160 x P 220 x Dz 110 mm, Svars: 2,3 kg, Tilpums: 3,8 litri",
    category: "Seifi",
    subcategory: "YALE",
  },
  {
    id: 17,
    imageUrl: "/static/images/products/YSS.250.EB1.jpg",
    slug: "gudrais-seifs-yss250eb1",
    title: "Gudrais Seifs YSS/250/EB1",
    price: 292,
    description: "Lielisks risinājums vērtīgo mantu glabāšanai – Smart Safe. Jums ir iespēja pārbaudīt, vai jūsu seifs ir atvērts vai slēgts, ar vienu pieskārienu jūsu viedtālrunī. Vairs nav jāuztraucas par pazudušām atslēgām vai aizmirsto PIN kodu. Varat sekot visām darbībām ar seifu, izmantojot diennakts Yale Home lietojumprogrammu. Tas nozīmē, ka vienmēr būsiet informēti par to, kas un kad ir atvēris jūsu Smart Safe. Specifikācija: Aizsardzības mehānisms: durvis ar lāzergriezumu un pretzāģēšanas bultām, lai aizsargātos pret uzbrukumiem, Lietojumprogrammas drošība: divu faktoru šifrēšana, biometriska verifikācija un divu faktoru autentifikācija, Tehnoloģija starp Smart Safe un viedtālruni: Bluetooth, Wi-Fi, Piekļuves tastatūra: koda ievadīšana, Atslēgas piekļuve: mehāniska darbība ar dubulto bitu atslēgu, Durvis: automātisks durvju atvēršanas mehānisms, Apgaismojums: iekšējais apgaismojums",
    category: "Seifi",
    subcategory: "YALE",
  },
  {
    id: 18,
    imageUrl: "/static/images/products/YLEB.200.EB1.jpg",
    slug: "yleb200eb1",
    title: "YLEB/200/EB1",
    price: 312,
    description: "Šis YLEB/200/EB1 augstas drošības motorizētais seifs, paredzēts portatīvajiem datoriem, piedāvā izcilu aizsardzību un drošību jūsu vērtīgajiem priekšmetiem. Tas ir aprīkots ar lāzera tehnoloģijā izgatavotām durvīm, kas pasargā pret instrumentu izmantošanu seifa atvēršanai. Ja trīs reizes tiek ievadīts nepareizs PIN kods, seifs vienu minūti tiek bloķēts, nodrošinot papildu drošību. Specifikācija: Aizsardzības mehānisms: lāzera tehnoloģijā izgatavotas durvis; pēc trim neveiksmīgiem mēģinājumiem seifs tiek bloķēts vienu minūti, Displejs: LCD tastatūras displejs, Apgaismojums: iekšējā gaisma, Ārējās dimensijas: A 200 x P 480 x Dz 350 mm, Iekšējās dimensijas: A 192 x P 475 x Dz 294,5 mm, Svars: 13,7 kg, Tilpums: 26,9 litri",
    category: "Seifi",
    subcategory: "YALE",
  },
  {
    id: 19,
    imageUrl: "/static/images/products/YSEB.250.EB1.jpg",
    slug: "yseb250eb1",
    title: "YSEB/250/EB1",
    price: 278,
    description: "Seifs YSEB/250/EB1 ir aprīkots ar lāzera tehnoloģijā izgatavotām durvīm, kas nodrošina aizsardzību pret uzbrukumiem, un augstas drošības mehānisko rezerves atslēgu, kas iekļauj vienu dubulto stienīšu atslēgu. Seifs ir aprīkots ar diviem pretzāģēšanas slēdžiem, lai nodrošinātu papildu drošību, un tam ir pieejama piekļuve ar PIN kodu. Pēc trim neveiksmīgiem PIN koda ievadīšanas mēģinājumiem seifs vienu minūti tiek bloķēts. Specifikācija: Aizsardzības mehānisms: lāzera tehnoloģijā izgatavotas durvis aizsardzībai pret uzbrukumiem; dubultā durtā atslēga; slēdža mehānisms ar diviem pretzāģēšanas slēdžiem (20 mm); PIN koda piekļuve, Displejs: LCD tastatūras displejs, Apgaismojums: iekšējā gaisma, Ārējās dimensijas: 250 x 350 x 300 mm, Iekšējās dimensijas: 242 x 345 x 245 mm, Svars: 12,1 kg, Tilpums: 20,5 litri",
    category: "Seifi",
    subcategory: "YALE",
  },
  {
    id: 20,
    imageUrl: "/static/images/products/YSEB.200.EB1.png",
    slug: "yseb200eb1",
    title: "YSEB/200/EB1",
    price: 250,
    description: "Seifs YSEB/200/EB1 ir aprīkots ar lāzera tehnoloģijā izgatavotām durvīm, kas nodrošina aizsardzību pret visiem uzbrukuma veidiem, kā arī automātisku durvju atvēršanas mehānismu un augstas drošības motorizētu slēdzi. Pēc trim neveiksmīgiem mēģinājumiem seifs vienu minūti tiek bloķēts, nodrošinot papildu drošību. Skaidrs LCD tastatūras displejs ļauj ērti ievadīt PIN kodu, bet iekšējā gaisma nodrošina labu redzamību. Seifā ir arī iekšējie āķi, paredzēti atslēgu vai mazu priekšmetu pakarināšanai. Specifikācija: Aizsardzības mehānisms: lāzera tehnoloģijā izgatavotās durvis; motorizētā slēdzene; pēc trim neveiksmīgiem mēģinājumiem seifs tiek bloķēts vienu minūti, Apgaismojums: iekšējā gaisma, Displejs: LCD tastatūras displejs, Iekšējās dimensijas: 192 x 345 x 145 mm, Ārējās dimensijas: 200 x 350 x 200 mm, Durvis: 145 x 300 mm, Tilpums: 9,6 litri, Svars: 8,5 kg",
    category: "Seifi",
    subcategory: "YALE",
  },
  {
    id: 21,
    imageUrl: "/static/images/products/Maksimālās drošības motorizētais seifs.jpg",
    slug: "maksimalas-drosibas-motorizetais-seifs-ysem520eg1",
    title: "Maksimālās drošības motorizētais seifs YSEM/520/EG1",
    price: 555,
    description: "YSEM/520/EG1 seifs piedāvā vairākas dažādas atvēršanas iespējas: piekļuve ar PIN kodu vai mehānisko atslēgu. Atvēršanas iespējas ir kombinētas ar ātrās piekļuves priekšrocībām un lāzera tehnoloģijā izgatavotām durvīm, kas nodrošina maksimālu aizsardzību. Pēc trim neveiksmīgiem mēģinājumiem seifs tiek bloķēts vienu minūti, nodrošinot papildu drošību pret nepilnvarotu piekļuvi. Specifikācija: Aizsardzības mehānisms: pastiprināts ar preturbjošo plāksni un lāzera tehnoloģijā izgatavotām durvīm, lai aizsargātos pret instrumentu izmantošanu seifa atvēršanai; pēc trim neveiksmīgiem mēģinājumiem seifs tiek bloķēts vienu minūti, Apgaismojums: iekšējā gaisma, Displejs: LCD tastatūras displejs, Ārējās dimensijas: A 520 x P 350 x Dz 360 mm, Iekšējās dimensijas: A 510 x P 337 x Dz 290 mm, Svars: 28 kg, Tilpums: 49,8 litri",
    category: "Seifi",
    subcategory: "YALE",
  },
  {
    id: 22,
    imageUrl: "/static/images/products/YSEM.400.EG1 Seifs.jpg",
    slug: "ysem400eg1-seifs",
    title: "YSEM/400/EG1 Seifs",
    price: 470,
    description: "YSEM/400/EG1 seifs piedāvā vairākas dažādas atvēršanas iespējas: piekļuve ar PIN kodu vai mehānisko atslēgu. Atvēršanas iespējas ir kombinētas ar ātrās piekļuves priekšrocībām un lāzera tehnoloģijā izgatavotām durvīm, kas nodrošina maksimālu aizsardzību. Pēc trim neveiksmīgiem mēģinājumiem seifs tiek bloķēts vienu minūti, nodrošinot papildu drošību pret nepilnvarotu piekļuvi. Specifikācija: Aizsardzības mehānisms: pastiprināts ar preturbjošo plāksni un lāzera tehnoloģijā izgatavotām durvīm, lai aizsargātos pret instrumentu izmantošanu seifa atvēršanai; pēc trim neveiksmīgiem mēģinājumiem seifs tiek bloķēts vienu minūti, Apgaismojums: iekšējā gaisma, Displejs: LCD tastatūras displejs ar PIN kodu, Ārējās dimensijas: A 400 x P 350 x Dz 340 mm, Iekšējās dimensijas: A 390 x P 337 x Dz 270 mm, Svars: 22 kg, Tilpums: 35,5 litri",
    category: "Seifi",
    subcategory: "YALE",
  },
  {
    id: 23,
    imageUrl: "/static/images/products/YLEM.200.EG1 Seifs.jpg",
    slug: "ylem200eg1-seifs",
    title: "YLEM/200/EG1 Seifs",
    price: 405,
    description: "Seifs YLEM/200/EG1 ir izstrādāts, lai nodrošinātu augstu drošības līmeni un lietošanas ērtību. Augstas drošības motorizētais slēdzis un slēgšanas sistēma garantē, ka jūsu vērtīgie priekšmeti ir drošībā. Pēc trim neveiksmīgiem mēģinājumiem seifs tiek bloķēts vienu minūti, nodrošinot papildu drošību pret nepilnvarotu piekļuvi. Specifikācija: Aizsardzības mehānisms: augstas drošības motorizētais slēdzis; pēc trim neveiksmīgiem mēģinājumiem seifs tiek bloķēts vienu minūti, Displejs: LCD tastatūras displejs, Apgaismojums: iekšējā gaisma, Ārējais 9 V terminālis (ja iekšējās baterijas ir izlādējušās, seifs var tikt atvērts), Iekšējās dimensijas: 190 x 467 x 280 mm, Ārējās dimensijas: 200 x 480 x 350 mm, Durvis: 145 x 424 mm, Tilpums: 24,8 litri, Svars: 18 kg",
    category: "Seifi",
    subcategory: "YALE",
  },
  {
    id: 24,
    imageUrl: "/static/images/products/Yale YSEM.250.EG1 Seifs.jpeg",
    slug: "yale-ysem250eg1-seifs",
    title: "Yale YSEM/250/EG1 Seifs",
    price: 370,
    description: "Šis seifs ir izveidots, lai nodrošinātu augstu drošības līmeni jūsu vērtīgo dokumentu un priekšmetu glabāšanai. Tas ir aprīkots ar motorizētu slēgšanas mehānismu, kas darbojas ar divām pret zāģēšanu izturīgām slēdzenēm, nodrošinot papildu aizsardzību pret nevēlamu iekļūšanu. Ja kāds mēģina piekļūt seifam, nepareizi ievadot PIN kodu, seifs automātiski tiek bloķēts vienu minūti, tādējādi nodrošinot papildu drošību pret nepilnvarotu piekļuvi. Specifikācija: Svars: 15,7 kg, Tilpums: 18,6 litri, Ārējās dimensijas: 250 x 350 x 300 mm, Iekšējās dimensijas: 240 x 337 x 230 mm, Displejs: LCD tastatūras displejs ar PIN koda piekļuvi, Aizsardzības mehānisms: Pret urbšanu izturīga plāksne un lāzera tehnoloģijā izgatavotas durvis nodrošina maksimālu drošības aizsardzību pret instrumentu izmantošanu, lai atvērtu seifu; pēc trim neveiksmīgiem mēģinājumiem seifs tiek bloķēts vienu minūti, Apgaismojums: iekšējā gaisma",
    category: "Seifi",
    subcategory: "YALE",
  },
  {
    id: 25,
    imageUrl: "/static/images/products/DS-KV6113-WPE1 ieejas videopanelis.jpg",
    slug: "ds-kvg113-wpe1-ieejas-videopanelis",
    title: "DS-KV6113-WPE1 ieejas videopanelis",
    price: 178.90,
    description: "DS-KV6113-WPE1 ir ūdensizturīgs metāla ieejas videopanelis ar integrētu kameru un mikrofonu. Tas piedāvā augstu izšķirtspēju un nodrošina skaidru attēlu pat naktī. Ar WDR un infrasarkano staru nakts redzamību tas ir lielisks risinājums piekļuves kontrolei jūsu īpašumā. Specifikācija: Produkta veids: ieejas videopanelis, Kameras izšķirtspēja: 1920 × 1080, Kadru ātrums: 1920 × 1080 ar ātrumu 30 kadri/sekundē, Diapazons: 3 m, Ražotājs: Hikvision",
    category: "Piekļuves tiesības",
    subcategory: "Videopanelis",
  },
  {
    id: 26,
    imageUrl: "/static/images/products/Trinity_HD_AHD_CVBS.jpg",
    slug: "trinity-hd-ahdcvbs-videonamruna-ieejas-panelis",
    title: "Trinity HD AHD/CVBS videonamruņa ieejas panelis",
    price: 67.90,
    description: "Trinity HD AHD/CVBS videonamruņa ieejas panelis nodrošina skaidru un drošu saziņu ar apmeklētājiem. Ar 2MP izšķirtspēju un 130° horizontālo skata leņķi tas sniedz skaidru un plašu redzamību. Izgatavots no alumīnija sakausējuma, tas ir izturīgs un ilgmūžīgs. Specifikācija: Produkta veids: videonamruņa ieejas panelis, Materiāls: alumīnija sakausējums, Skata leņķis: 130°, Apgaismojums: LED, Darbības temperatūra: -30 – +50 °C, Izmēri: garums 133 mm, platums 48 mm, augstums 17 mm",
    category: "Piekļuves tiesības",
    subcategory: "Trinity",
  },
  {
    id: 27,
    imageUrl: "/static/images/products/DS-K1T680DG.png",
    slug: "sejas-atpazisanas-terminalis-ds-k1t680dg",
    title: "Sejas atpazīšanas terminālis DS-K1T680DG",
    price: 499.80,
    description: "DS-K1T680DG sejas atpazīšanas terminālis ir lielisks lielu uzņēmumu vajadzībām. Ar iespēju uzglabāt līdz pat 100 000 seju, 100 000 karšu un reģistrēt 150 000 notikumu šis terminālis nodrošina augstu drošības līmeni. Tam ir dažādas savienojuma opcijas, kas ļauj integrēt to ar esošajām sistēmām, un tas piedāvā lielu atpazīšanas ātrumu un augstu precizitāti. Specifikācija: Atpazīšanas attālums: no 0,3 līdz 3 m, Atpazīšanas ātrums: 0,2 sekundes, precizitāte ≥ 99%, Audio: divvirzienu, Ekrāns: astoņu collu kapacitīvs skārienekrāns, Atmiņa: 1500 pirkstu nospiedumu, 1500 seju atmiņa, 1500 karšu atmiņa un 150 000 notikumu ietilpība, Ražotājs: HikVision",
    category: "Piekļuves tiesības",
    subcategory: "Sejas atpazīšanas terminālis",
  },
  {
    id: 28,
    imageUrl: "/static/images/products/D40.jpg",
    slug: "d-40-autonomais-kontrolieris-ar-nolasijsu-un-sifreju",
    title: "D-40 autonomais kontrolieris ar nolasītāju un šifrēju",
    price: 298.99,
    description: "D-40 kontrollers ar nolasītāju un šifrētāju ir piemērots ārējai instalācijai, nodrošinot drošību un piekļuvi telpām vai teritorijai. Tas darbojas ar EM 125 KHz frekvenci un var uzglabāt līdz pat 2000 lietotāju. Viegli uzstādāms un lietojams, šis kontrollers nodrošina drošu un vienkāršu piekļuves kontroli jebkurā situācijā. Cena ir norādīta par visu komplektu, un katram klientam cena var atšķirties. Specifikācija: Instalācijas veids: ārējais, Nolasītāja frekvence: EM 125 KHz, Lietotāju skaits: 2000, Darba spriegums: 12 VDC, Nolasītāja darbības attālums: 3–6 cm, Atmiņa: līdz 2000 kartītēm un kodiem, Darbības frekvence: EM 125 kHz, Aizsardzība: IP68",
    category: "Piekļuves tiesības",
    subcategory: "D-40",
  },
  {
    id: 29,
    imageUrl: "/static/images/products/EZVIZ DP2C Bezvadu durvju actiņa ar monitoru.jpg",
    slug: "ezviz-dp2c-bezvadu-durvju-actiņa-ar-monitoru",
    title: "EZVIZ DP2C Bezvadu durvju actiņa ar monitoru",
    price: 198.99,
    description: "EZVIZ DP2C ir novatorisks komplekts, kas apvieno durvju kameras un zvaniņa funkciju vienā ierīcē. Ar iekšējo krāsaino monitoru varēsiet ne tikai identificēt apmeklētājus, bet arī sazināties ar tiem. Iespēja saņemt brīdinājumus par potenciāli aizdomīgu aktivitāti tieši uz jūsu mobilo ierīci padara šo komplektu par lielisku risinājumu jūsu mājas drošībai un komfortam. Stilīgs, mūsdienīgs dizains, ātra uzstādīšana un viegla savienojamība ar jūsu mobilo ierīci, izmantojot mājas Wi-Fi tīklu. Specifikācija: Video: 1080 p, Skata leņķis: 155°, Ekrāns: 4,3 collu, krāsains, Akumulators: 4600 mAh uzlādējams litija akumulators, Apgaismojums: līdz 5 m, Atmiņas kartes atbalsts: MicroSD (līdz 256 GB), Ražotājs: EZVIZ",
    category: "Piekļuves tiesības",
    subcategory: "Domofoni",
  },
  {
    id: 30,
    imageUrl: "/static/images/products/TEDEE durvju atvēršanas tastatūra ar PIN kodu.png",
    slug: "tedee-durvju-atversanas-tastatura-ar-pin-kodu",
    title: "TEDEE durvju atvēršanas tastatūra ar PIN kodu",
    price: 105,
    description: "Standarta uzticams produkts jūsu drošības vajadzībām. Aprīkots ar TKV 1.0 modeli, kas nodrošina atbloķēšanu ar PIN kodu un darbojas ar baterijām. Sistēma ļauj iestatīt līdz 100 aktīviem PIN kodiem, un, pateicoties vienkāršajai lietošanai, nav nepieciešama papildu lietotne piekļuves kodu kopīgošanai, tādējādi izslēdzot datu uzglabāšanas risku. Ierīces kompaktie izmēri ir 48 x 135 x 28 mm, ar svaru 120 g bez baterijām vai 155 g ar trim AAA baterijām, kas iekļautas komplektā. Aprīkots ar modernu Bluetooth BLE 5.0 (2,4 GHz) saziņu un IP65 aizsardzības klasi pret ārējās vides iedarbību.",
    category: "Slēdzenes",
    subcategory: "TEDEE",
  },
  {
    id: 31,
    imageUrl: "/static/images/products/Papildu drošības slēdzenes.jpg",
    slug: "papildu-drosibas-sledzenes",
    title: "Papildu drošības slēdzenes",
    price: 120,
    description: "Papildu drošības slēdzene, uzstādāma uz iekšdurvīm, nodrošinot papildu aizsardzību gadījumā, ja pamatslēdzene tiek uzlauzta. Pieejami dažādi drošības līmeņi un risinājumi atbilstoši klienta vajadzībām. Lūdzu, sazinieties ar mums, lai precizētu detaļas.",
    category: "Slēdzenes",
    subcategory: "Slēdzenes nomaiņa",
  },
];